# Generated by Django 3.2.8 on 2021-11-15 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid_vaccination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_token_id', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('covid_affected', models.CharField(max_length=5)),
                ('symptoms', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=150)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
