# Generated by Django 3.2.11 on 2022-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_vaccination_app', '0003_auto_20211115_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationbooking',
            name='symptoms',
            field=models.TextField(null=True),
        ),
    ]
